import oracledb
from config.db_config import get_connection

def create_table():
    ddl = """
    CREATE TABLE colheita_cana (
        id_colheita NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        produtor_nome VARCHAR2(100) NOT NULL,
        fazenda_nome VARCHAR2(100),
        hectares_colhidos NUMBER(10, 2),
        perda_estimativa_percentual NUMBER(5, 2),
        metodo_colheita VARCHAR2(20), -- 'manual' ou 'mecanica'
        data_colheita DATE DEFAULT SYSDATE
    )
    """

    conn = get_connection()
    if conn:
        try:
            with conn.cursor() as cur:
                cur.execute("BEGIN EXECUTE IMMEDIATE 'DROP TABLE colheita_cana'; EXCEPTION WHEN OTHERS THEN NULL; END;")
                cur.execute(ddl)
                conn.commit()
                print("Tabela criada com sucesso.")
        except Exception as e:
            print("Erro ao criar tabela:", e)
        finally:
            conn.close()

if __name__ == "__main__":
    create_table()